### ISSUE TITLE
[Suggestion] Output to Discord

### ISSUE THREAD

**Issue by MoonieGZ** [zvyap/hoyoverse-github-action-daily-checkin#1]
Hi!
Love the look of the project so far, I'd love to see some pushing to Discord webhooks similar to this
![image](https://github.com/zvyap/hoyoverse-github-action-daily-checkin/assets/1693101/64878d1d-8282-49ca-9cf3-c92d11540312)

(from an outdated solution here: https://github.com/vermaysha/Hoyolab-Auto-Daily-Checkin )

Is this something you've considered or would be willing to throw in?

Appreciate it!

**Comment by zvyap** [comment]
Sure.

**Comment by zvyap** [comment]
Done #2
Check 
https://github.com/zvyap/hoyoverse-github-action-daily-checkin/wiki/Update-this-project-to-your-fork
and 
https://github.com/zvyap/hoyoverse-github-action-daily-checkin/wiki/Discord-Webhook
